spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/manager"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: "chaveSecretaMuitoSeguraParaGerarJWT"
    expiration: 36000

##  security:
##    user:
##      name: "admin"
##      password: "admin"

## Para custumizar o caminho da documentação.
##springdoc:
##  api-docs:
##    path: /api-docs
##  swagger-ui:
##    path: /swagger-ui.html
